---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 750346026758893568-dSIzIZCfbgrEtTU1xCupdIjchJATkr6
:access_token_secret: b4eNEAxS24TM3rFfxzbrBsbQHTS0cKY4HJeedYcMylxiy
